### ISSUE TITLE
direct JSON input

### ISSUE THREAD

**Issue by SergioCrisostomo** [theiviaxx/MilkChart#34]
Hi Brett, 

I have a project where I get a JSON object with alot of info passed to client side and I want to get the data for the Milkchart on the client-side. So, I added this to my repo: https://github.com/SergioCrisostomo/MilkChart/blob/directJSON/Source/MilkChart_src.js#L476-L482 - fiddle:  http://jsfiddle.net/T4Fy2/

Question: is this interesting for your repo? is there a better way to do this?

**Comment by theiviaxx** [comment]
Does the json data come from a request or is i baked into the page?  If
it's baked in, you could add the .render() method to the end of .setData()
instead of adding a new function.  If it is from a request, just use the
.load() method and provide an onLoad handler to transform the data.

On Sun, Dec 22, 2013 at 2:45 PM, Sergio Crisostomo <notifications@github.com

**Comment by SergioCrisostomo** [comment]
@theiviaxx that was much better. I think the docs could have this info more clear for others like me. Can I make a PR for this? https://github.com/SergioCrisostomo/MilkChart/commit/6b8fa04268d81b436cc0bbc5c44bfe40eedbb6f5

**Comment by theiviaxx** [comment]
The docs have the load function mentioned

**Comment by SergioCrisostomo** [comment]
@theiviaxx  Yes, but not the json structure. Was just an idea.

**Comment by theiviaxx** [comment]
I see, yeah i can update the docs for that

Thanks

**Comment by SergioCrisostomo** [comment]
@theiviaxx great. Thanks for a nice app!
